# Generated by Django 4.2 on 2023-04-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('nombre_usuario', models.CharField(max_length=255, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('contrasena', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion_despacho', models.TextField(blank=True, max_length=255, null=True, verbose_name='Dirección de despacho')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'core_usuario',
            },
        ),
    ]

