# Generated by Django 4.2 on 2023-05-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resena_xbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena_Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='post_images')),
                ('contenido', models.TextField()),
            ],
        ),
    ]
